# Use the official Python runtime as the base image
FROM python:3.11-slim

# Set the working directory in the container
WORKDIR /app

# Install any necessary dependencies
RUN apt-get update && \
    apt-get install -y zip && \
    rm -rf /var/lib/apt/lists/*

# Copy the requirements file to the working directory
COPY layer_requirements.txt .

# Install the Python packages listed in requirements.txt
RUN pip install -r layer_requirements.txt -t /opt/python/ && \
    cd /opt && \
    zip -r9 /app/pandasrequests_layer.zip .

# Set the CMD to zip the installed packages into a layer
# change the `requests-layer` to the LAYER_NAME variable as per create_layer.sh file

CMD ["/bin/bash"]